spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card_services_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Admin123$
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  data:
    redis:
      host: localhost
      port: 6379
      password: ''
      timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
app:
  services:
    bin: 511420
    account:
      base-url: http://localhost:8080/api/accounts