server:
  port: 8080
spring:
  application:
    name: card-service-v1.0
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
app:
  services:
    customer:
      base-url: http://localhost:8081/api/customers
    card:
      base-url: http://localhost:8082/api/cards
